// templates/template-svelte/src/components/ContractVote.svelte
<script>
  import { isConnected, request } from "@stacks/connect";
  import { Cl } from "@stacks/transactions";

  export async function vote(pick) {
    try {
      const result = await request("stx_callContract", {
        contract: "ST39MJ145BR6S8C315AG2BD61SJ16E208P1FDK3AK.example-fruit-vote-contract",
        functionName: "vote",
        functionArgs: [Cl.stringUtf8(pick)],
        postConditions: [],
        postConditionMode: "deny",
        network: "testnet",
      });
      console.log("result:", result);
      window
        .open(
          `https://explorer.hiro.so/txid/${result.txid}?chain=testnet`,
          "_blank"
        )
        ?.focus();
    } catch (e) {
      console.error(e);
    }
  }

  let connected = isConnected();
</script>

{#if connected}
  <div>
    <p>Vote via Smart Contract</p>
    <button on:click={() => vote("🍊")}> Vote for 🍊 </button>
    <button on:click={() => vote("🍎")}> Vote for 🍎 </button>
  </div>
{/if}

<style>
  div {
    margin-top: 16px;
  }
</style>

// templates/template-angular/src/app/contract-vote/contract-vote.ts
import { Component, inject } from '@angular/core';
import { request } from '@stacks/connect';
import { Cl } from '@stacks/transactions';
import { StacksService } from '../stacks.service';

const CONTRACT = 'ST39MJ145BR6S8C315AG2BD61SJ16E208P1FDK3AK.example-fruit-vote-contract';

@Component({
  selector: 'app-contract-vote',
  templateUrl: './contract-vote.html',
  styleUrl: './contract-vote.css',
})
export class ContractVote {
  protected readonly stacks = inject(StacksService);

  async vote(pick: string): Promise<void> {
    try {
      const response = await request('stx_callContract', {
        contract: CONTRACT,
        functionName: 'vote',
        functionArgs: [Cl.stringUtf8(pick)],
        network: 'testnet',
      });
      console.log('txid:', response.txid);
      window
        ?.open(`https://explorer.hiro.so/txid/${response.txid}?chain=testnet`, '_blank')
        ?.focus();
    } catch (error) {
      console.error('Transaction was canceled or failed:', error);
    }
  }
}
