// templates/template-svelte-ts/src/App.svelte
<script lang="ts">
  import ConnectWallet from './components/ConnectWallet.svelte'
  import ContractVote from './components/ContractVote.svelte'
</script>

<section id="center">
  <h1>Svelte + Stacks.js</h1>
  <p>Edit <code>src/App.svelte</code> to get started.</p>

  <!-- ConnectWallet file: `./src/components/ConnectWallet.svelte` -->
  <ConnectWallet />

  <!-- ContractVote file: `./src/components/ContractVote.svelte` -->
  <ContractVote />

  <p>
    <a href="https://docs.hiro.so/stacks.js" target="_blank" rel="noreferrer">
      Stacks.js documentation
    </a>
  </p>
</section>

// templates/template-vue/src/App.vue
<script setup>
import StacksConnectWallet from './components/StacksConnectWallet.vue'
import StacksContractVote from './components/StacksContractVote.vue'
</script>

<template>
  <h1>Stacks.js + Vue</h1>
  <p>Edit <code>src/App.vue</code> to get started.</p>

  <StacksConnectWallet />
  <StacksContractVote />

  <p>
    <a href="https://docs.hiro.so/stacks.js" target="_blank">Stacks.js docs</a>
  </p>
</template>
