// templates/template-svelte-ts/src/App.svelte
<script lang="ts">
  import ConnectWallet from './components/ConnectWallet.svelte'
  import ContractVote from './components/ContractVote.svelte'
</script>

<section id="center">
  <h1>Svelte + Stacks.js</h1>
  <p>Edit <code>src/App.svelte</code> to get started.</p>

  <!-- ConnectWallet file: `./src/components/ConnectWallet.svelte` -->
  <ConnectWallet />

  <!-- ContractVote file: `./src/components/ContractVote.svelte` -->
  <ContractVote />

  <p>
    <a href="https://docs.hiro.so/stacks.js" target="_blank" rel="noreferrer">
      Stacks.js documentation
    </a>
  </p>
</section>

// templates/template-react-vite/src/App.jsx
import './App.css'
import ConnectWallet from './components/ConnectWallet'
import ContractCallVote from './components/ContractCallVote'

function App() {
  return (
    <section id="center">
      <h1>Vite + React + Stacks.js</h1>
      <p>
        Edit <code>src/App.jsx</code> and save to test HMR
      </p>

      <ConnectWallet />
      <ContractCallVote />

      <p>
        <a href="https://docs.hiro.so/stacks.js">Stacks.js docs</a>
      </p>
    </section>
  )
}

export default App
