// templates/template-react-nextjs/app/page.js
import styles from "./page.module.css";
import ConnectWallet from "./components/ConnectWallet";
import ContractCallVote from "./components/ContractCallVote";

export default function Home() {
  return (
    <div className={styles.page}>
      <main className={styles.main}>
        <div className={styles.intro}>
          <h1>Next.js + Stacks.js</h1>
          <p>
            Connect a Stacks wallet and call a smart contract. Start editing the
            components in <code>app/components</code>.
          </p>
          <a href="https://docs.hiro.so/stacks.js" target="_blank" rel="noopener noreferrer">
            Stacks.js docs
          </a>
        </div>

        {/* ConnectWallet file: `./app/components/ConnectWallet.js` */}
        <ConnectWallet />

        {/* ContractCallVote file: `./app/components/ContractCallVote.js` */}
        <ContractCallVote />
      </main>
    </div>
  );
}

// templates/template-svelte/src/App.svelte
<script>
  import ConnectWallet from './components/ConnectWallet.svelte'
  import ContractVote from './components/ContractVote.svelte'
</script>

<main>
  <h1>Svelte + Stacks.js</h1>

  <!-- ConnectWallet file: `./src/components/ConnectWallet.svelte` -->
  <ConnectWallet />

  <!-- ContractVote file: `./src/components/ContractVote.svelte` -->
  <ContractVote />

  <p>
    <a href="https://docs.hiro.so/stacks.js" target="_blank" rel="noreferrer">Stacks.js docs</a>
  </p>
</main>
