// templates/template-svelte-ts/src/components/ConnectWallet.svelte
<script lang="ts">
  import {
    connect,
    disconnect,
    getLocalStorage,
    isConnected,
  } from "@stacks/connect";
  import { onMount } from 'svelte';

  let connected = false;
  let address = '';

  function updateState() {
    connected = isConnected();
    const storage = getLocalStorage();
    if (connected && storage && storage.addresses?.stx?.[0]?.address) {
      address = storage.addresses.stx[0].address;
    }
  }

  onMount(() => {
    updateState();
  });

  async function authenticate() {
    await connect({
      network: "testnet",
    });
    updateState();
  }

  function handleDisconnect() {
    disconnect();
    updateState();
  }
</script>

<div>
  {#if connected}
    <button on:click={handleDisconnect}> Disconnect Wallet </button>
    <p>STX Address: {address}</p>
  {:else}
    <button on:click={authenticate}> Connect Wallet </button>
  {/if}
</div>

<style>
  div {
    margin-top: 8px;
  }
</style>

// templates/template-react-vite-ts/src/components/ConnectWallet.tsx
import {
  connect,
  disconnect,
  getLocalStorage,
  isConnected,
  request,
} from "@stacks/connect";
import { useState } from "react";

const ConnectWallet = () => {
  const [, setRefresh] = useState(0);
  const refresh = () => setRefresh((n) => n + 1);
  const storage = getLocalStorage();

  if (isConnected() && storage) {
    return (
      <div>
        <button
          className="Connect"
          onClick={() => {
            disconnect();
            refresh();
          }}
        >
          Disconnect Wallet
        </button>
        <p>BTC Address: {storage.addresses.btc[0].address}</p>
        <p>STX Address: {storage.addresses.stx[0].address}</p>
      </div>
    );
  }

  return (
    <button
      className="Connect"
      onClick={async () => {
        await request("getAddresses", {
          network: "testnet",
        });
        refresh();
      }}
    >
      Connect Wallet
    </button>
  );
};

export default ConnectWallet;
