// templates/template-vue-ts/src/App.vue
<script setup lang="ts">
import StacksConnectWallet from './components/StacksConnectWallet.vue'
import StacksContractVote from './components/StacksContractVote.vue'
</script>

<template>
  <h1>Vite + Vue + Stacks.js</h1>

  <StacksConnectWallet />
  <StacksContractVote />

  <p>
    Edit <code>src/components/StacksContractVote.vue</code> to change the contract call.
  </p>
  <p>
    <a href="https://docs.hiro.so/stacks.js" target="_blank">Stacks.js documentation</a>
  </p>
</template>

// templates/template-react-vite-ts/src/App.tsx
import './App.css'
import ConnectWallet from './components/ConnectWallet'
import ContractCallVote from './components/ContractCallVote'

function App() {
  return (
    <main>
      <h1>Vite + React + Stacks.js</h1>
      <p>
        Edit <code>src/App.tsx</code> and save to test HMR.
      </p>

      {/* ConnectWallet file: `./src/components/ConnectWallet.tsx` */}
      <ConnectWallet />

      {/* ContractCallVote file: `./src/components/ContractCallVote.tsx` */}
      <ContractCallVote />

      <p>
        <a href="https://docs.hiro.so/stacks.js" rel="noopener noreferrer" target="_blank">
          Stacks.js documentation
        </a>
      </p>
    </main>
  )
}

export default App
